# Generated by Django 4.0.1 on 2022-01-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_basket_basketitem_basket_books_basket_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
