# Generated by Django 4.0.1 on 2022-01-20 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('favorite', '0003_remove_basketitem_basket_remove_basketitem_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_books', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('img', models.CharField(max_length=200)),
                ('book', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(max_length=400)),
                ('source', models.CharField(max_length=50)),
                ('article', models.UUIDField(default=uuid.uuid4)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorite.basket')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorite.customer')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='favorite_basket', to='favorite.BasketItem'),
        ),
        migrations.AddField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorite.customer'),
        ),
    ]
