# Generated by Django 4.0.1 on 2022-01-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0004_basket_basketitem_basket_books_basket_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='object_id',
        ),
    ]
