# Generated by Django 4.0.1 on 2022-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0006_alter_basket_books_alter_basketitem_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
